### ISSUE TITLE
Overlapping emoji with specific line spacing

### ISSUE THREAD

**Issue by crostine** [morkro/atom-emoji-syntax#34]
hi

i noticed the lineheight is incorrect when emojis are inserted
![linewraperror](https://cloud.githubusercontent.com/assets/5873080/20525369/67f1795c-b0bf-11e6-8e7d-ab4092519f37.png)
line 19 is empty in both cases..

my lineheight is 1.3; fontsize 12

looks like the linespacing isnt corrected for the emoji size or the other way around, emoji size to the linesize
also it seems to correct itself after a few lines with no emojis

**Comment by crostine** [comment]
lineheight of 1.75 is my temporary solution ;)

**Comment by morkro** [comment]
Which OS are you using? Do you have the latest Atom version installed?

I am not quite sure I completely follow the problem. The issue are the "touching" emoji because of an incorrect line height?  The line height seems to be different in both screenshots; is the lower screenshot _after_ you applied a line height of `1.75`? 😃

**Comment by crostine** [comment]
im on windows 10,

both screenshots are the same but with the emoji package enabled and disabled.

**Comment by morkro** [comment]
Ah, now I get it. Thanks!
I am currently updating the settings page, and will look into your issue right after 🎉

**Comment by morkro** [comment]
Hey @crostine,

the issue is fixed in the current development [branch](/morkro/atom-emoji-syntax/tree/settings-design-update) with commit eb471fbf47ef7561b9940a26dbd3599ae6b2b90b and will be published in the [next release](https://github.com/morkro/atom-emoji-syntax/projects/1) 🎉

**Comment by crostine** [comment]
cheers for the fix,
however 1.3em still overlaps some lines when using lineheight 1.3 ;P

With the stylesheet edited to 1.3em makes it fixed for lineheights >= 1.4
1.2em and 1.3 lineheight: every 6th line overlaps by a few (1-3 depending on zoom) pixels 
1.1em and 1.3 lineheight: same as 1.2em
1em seems to fix it for 1.3 lineheight but lowering the lineheight further makes lines overlap again

It looks like the emoji is bigger than the line but gets drawn from the top of the line and sticks out under the line forcing the next line to be drawn a few pixels lower. But the selected line highlighter or the cursor will never allign with these 'moved' lines. So I get the feeling this is not something in this package but rather in atom itself.

I'm going to hardcode my emoji size to 1em and leave it like that.

**Comment by morkro** [comment]
Ah dammit, I see what you mean. I might be able to fix it though with some CSS adjustments. 

I would still like to see this fixed sooner or later, so you don't have to hardcore the size yourself. Maybe I have to add an option in the package settings or something. 

Thanks anyway for your investigations! 🎉

**Comment by crostine** [comment]
This is still happening, but this time i figured out what is causing it for real!
![emoji](https://cloud.githubusercontent.com/assets/5873080/21930110/9926e176-d994-11e6-939e-2b861721ea14.png)

```
lineHeight    lineNumberHeight    fontSize    emojiSize
1             12                  15          15.59
1.1           13                  15          15.59
1.2           14                  15          15.59
1.3           15                  15          15.59
1.4           16                  15          15.59
1.5           18                  15          15.59
```

**Comment by morkro** [comment]
Thanks a lot @crostine! I will re-open the issue so I can keep track of it and properly fix it :)

**Comment by morkro** [comment]
Hey @crostine , I think I fixed the line-height related issue. Can you please update the package to the latest release and check? :)

**Comment by crostine** [comment]
hey, cheers for still trying to fix this, it seems to work great for any lineheight > 1.1 which is very common I guess. 
However if you change the line height to < 1 it starts overlapping again.
![almost correct](https://cloud.githubusercontent.com/assets/5873080/23505867/bd61f6bc-ff45-11e6-8d01-67fb78966d3c.PNG)

the following change fixes it, which is correct I think. 
`lib/stylesheet.js:18      "height: auto;"`
`lib/stylesheet.js:18      "height: inherit;"`
![correct](https://cloud.githubusercontent.com/assets/5873080/23506049/8391fecc-ff46-11e6-86b3-02e4929e679c.PNG)
This works even on smaller sizes than 1.
But it no longer scales with the line size only with font size

**Comment by morkro** [comment]
Ha, interesting. It seemed to work fine for me with line height at `1`. Let me try out your solution, hope that fixes it forever :D

**Comment by crostine** [comment]
I'm closing this issue as I am not seeing this problem anymore.

**Comment by morkro** [comment]
Awesome, that makes me happy 🎉
